name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - subbranch
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_KEY }}
    
    - name: Build Docker Image
      run: docker build -t vineeth1927/closer-server .
    
    - name: Publish Image to docker hub
      run: docker push vineeth1927/closer-server:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
     - name: Pull image from docker hub
       run: docker pull vineeth1927/closer-server:latest
     - name: Delete old container
       run: docker rm -f nodejs-app-container
     - name: Run Docker Container
       run: docker run -d -p 5000:5000 --name nodejs-app-container vineeth1927/closer-server
